services:
  s3mock:
    image: adobe/s3mock
    ports:
      - '9090:9090'
    environment:
      - initialBuckets=boilerplate-local-media-bucket
      - S3MOCK_HTTPS=0
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      - ./docker-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/'
  cognito:
    image: jagregory/cognito-local
    container_name: cognito-local
    ports:
      - "9229:9229" # Expose the local Cognito port
    environment:
      - AWS_REGION=us-east-1 # Set AWS region for local testing
    volumes:
      - ./data:/app/data # Persist data across restarts
volumes:
  #s3mock-data:
  dynamodb-data:
