AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying a Lambda function using a Docker image.

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: boilerplate-local-express
      PackageType: Image
      ImageUri: boilerplate-local-express
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Sub "${COGNITO_USER_POOL_ID}"
          COGNITO_CLIENT_ID: !Sub "${COGNITO_CLIENT_ID}"
